repository: ${GITHUB_REPOSITORY}/benchmark
coverage:
  if: false
codeToTestRatio:
  if: false
testExecutionTime:
  if: false
diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}/benchmark
comment:
  if: is_pull_request
summary:
  if: true
