repository: ${GITHUB_REPOSITORY}/benchmark
coverage:
  if: false
codeToTestRatio:
  if: false
testExecutionTime:
  if: false
report:
  if: is_pull_request
  datastores:
    - local://benchmark.main.json
